CREATE SCHEMA RAZVOJ;
CREATE TABLE RAZVOJ.VRSTA_PUBLIKACIJE
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO RAZVOJ.VRSTA_PUBLIKACIJE (naziv) VALUES ('ELEKTRONICKA');
INSERT INTO RAZVOJ.VRSTA_PUBLIKACIJE (naziv) VALUES ('PAPIRNATA');

CREATE TABLE RAZVOJ.JEZIK
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(20) NOT NULL,
PRIMARY KEY (id) 
);

INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('HRVATSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('ENGLESKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('NJEMACKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('FRANCUSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('TALIJANSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('RUSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('KINESKI');

CREATE TABLE RAZVOJ.IZDAVAC
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(50) NOT NULL,
drzava VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO RAZVOJ.IZDAVAC (naziv, drzava) VALUES ('Školska knjiga', 'Hrvatska');
INSERT INTO RAZVOJ.IZDAVAC (naziv, drzava) VALUES ('Packt Publishing', 'SAD');

CREATE TABLE RAZVOJ.KNJIGA
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(50) NOT NULL,
godinaIzdanja INT NOT NULL,
vrstaPublikacije INT NOT NULL,
brojStranica INT NOT NULL,
jezik INT NOT NULL,
izdavac INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (vrstaPublikacije) REFERENCES RAZVOJ.VRSTA_PUBLIKACIJE(id),
FOREIGN KEY (jezik) REFERENCES RAZVOJ.JEZIK(id),
FOREIGN KEY (izdavac) REFERENCES RAZVOJ.IZDAVAC(id)
);

INSERT INTO RAZVOJ.KNJIGA (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, jezik, 
izdavac) VALUES ('Programiranje u Javi', 2014, 1, 400, 1, 1);
INSERT INTO RAZVOJ.KNJIGA (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, jezik, 
izdavac) VALUES ('Java web applications', 2014, 2, 600, 2, 2);

CREATE TABLE RAZVOJ.CASOPIS
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(20) NOT NULL,
godinaIzdanja INT NOT NULL,
vrstaPublikacije INT NOT NULL,
brojStranica INT NOT NULL,
mjesecIzdanja INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (vrstaPublikacije) REFERENCES RAZVOJ.VRSTA_PUBLIKACIJE(id)
);

INSERT INTO RAZVOJ.CASOPIS (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, 
mjesecIzdanja) VALUES ('Bug', 2014, 2, 200, 5);
INSERT INTO RAZVOJ.CASOPIS (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, 
mjesecIzdanja) VALUES ('Java Magazine', 2014, 2, 100, 5);

CREATE TABLE RAZVOJ.CLAN
( 
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
oib CHAR(11) NOT NULL,
ime VARCHAR(50) NOT NULL,
prezime VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO RAZVOJ.CLAN (oib, ime, prezime) VALUES ('12334534512', 'Pero', 'Periæ');
INSERT INTO RAZVOJ.CLAN (oib, ime, prezime) VALUES ('44332211221', 'Ivo', 'Iviæ');

CREATE TABLE RAZVOJ.POSUDBA_KNJIGA
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
clan INT NOT NULL,
knjiga INT NOT NULL,
datumPosudbe DATE NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (clan) REFERENCES RAZVOJ.CLAN(id),
FOREIGN KEY (knjiga) REFERENCES RAZVOJ.KNJIGA(id)
);

CREATE TABLE RAZVOJ.POSUDBA_CASOPISA
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
clan INT NOT NULL,
casopis INT NOT NULL,
datumPosudbe DATE NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (clan) REFERENCES RAZVOJ.CLAN(id),
FOREIGN KEY (casopis) REFERENCES RAZVOJ.CASOPIS(id)
);